import { Inter } from "next/font/google";
import "../styles/globals.css";
import "../styles/bootstrap-datetimepicker.min.css";
import "../styles/feather.css";
import "../styles/owl.theme.default.min.css";
import "../styles/slick.css";
import "../styles/bootstrap.min.css";
import "../styles/style.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
